server {
    listen 80;
    listen [::]:80;
    server_name 154.64.254.52;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        default_type text/plain;
    }

    location / {
        return 404;
    }
}
